import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import { AuthContext } from './_app'
import { Typography } from '@material-ui/core'

export default function Home() {

  const {currentUser,isSignedIn} = useContext(AuthContext)

  return (
    <>
      <Head>
        <title>liberta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
       {isSignedIn&&<Typography>hello next  {currentUser?.name}</Typography>}
      </main>
    </>
  )
}
